# Generated by Django 4.0.4 on 2022-08-14 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(max_length=200)),
                ('image_link', models.CharField(blank=True, max_length=200, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
